sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.android
jdk: oraclejdk7
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-19.1
    - android-16
    - extra
    - extra-google-m2repository
    - extra-android-m2repository
before_script:
  - ./gradlew --version
script: ./gradlew -S -Dscan build jacocoTestReport jacocoRootReport
after_success:
  - ./gradlew coveralls
